### ISSUE TITLE
The archivist can edit a collection label.

### ISSUE THREAD

**Issue by bb233** [cul-it/archival-storage-interface#13]
See Use Case 1 of https://confluence.cornell.edu/pages/viewpage.action?pageId=340904277

The original use case document was uncertain as to the need for this. Offhand, it does not fit well with the overflow storage model, where the collection label is embedded in the storage system.

**Comment by e2d2** [comment]
I'm not sure that this is needed. If there's a need to change collection labels, it'd be a big change that I wouldn't want to see done through this interface.

**Comment by zimeon** [comment]
I agree with @e2d2's comment -- this seems out of scope for the current interface pilot because it means editing the archival information in some way

**Comment by bb233** [comment]
OK, I'll close this issue.
